### ISSUE TITLE
Add documentation and setup rustdoc

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/tofn#131]
Most of the documentation is only in the README. We should [setup rustdoc](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) and progressively start adding documentation everywhere.

**Comment by ef3n9r98** [comment]
Hey @ggutoski and @milapsheth, I know some devs who'd love to work on this. If you're still looking for PRs on this issue, is there a budget for fixing this issue, and if so, how much?
