### ISSUE TITLE
Use k256 native serde support

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofn#197]
The next release of `k256` will support `serde`.
https://github.com/RustCrypto/elliptic-curves/pull/464
With that we can delete our `k256_serde` module! 🥳

**Comment by tarcieri** [comment]
`k256` v0.10.0 is out with native `serde` support:

- https://crates.io/crates/k256/0.10.0
- https://docs.rs/k256/latest/k256/#serde-support

**Comment by thor314** [comment]
We've forked this library, and updated dependencies. Would you accept a pull request updating them? @ggutoski

**Comment by ggutoski** [comment]
Sure!  Happy to take a look.  Updating dependencies has been on the to-do list for a while.

**Comment by thor314** [comment]
alright. Need to clean up a bit, and a pull is on the way.

**Comment by thor314** [comment]
pull is here https://github.com/axelarnetwork/tofn/pull/203

**Comment by thor314** [comment]
@tarcieri, looks like k256 supports serialization for `AffinePoint`, `Scalar,` and `VerifyingKey`, but not `ProjectivePoint`. Why is that?

**Comment by tarcieri** [comment]
@thor314 probably an oversight, although FWIW the implementation would be converting the `ProjectivePoint` to an `AffinePoint` and serializing that.

`ProjectivePoint` is a convenient representation for arithmetic, whereas `AffinePoint` is more of the "serialization type"

**Comment by thor314** [comment]
@tarcieri, simple enough. Would it be helpful if I submitted a pull to k256 with that feature?

**Comment by tarcieri** [comment]
sure, that's fine. however `master` has the v0.11.0-pre branch of `k256` and we don't have separate branches for older versions, so it won't get into `k256` until the next release

**Comment by thor314** [comment]
@tarcieri what branch should I submit the k256 feature to?

**Comment by tarcieri** [comment]
`master`

**Comment by milapsheth** [comment]
moved to jira
