### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by naughtyfox** [axelarnetwork/tofn#199]
Hey guys! 
We'd like to use tofn library, but it has no releases or version tags. How about adding ones? 
Thank you for awesome product!

**Comment by ggutoski** [comment]
Hi!  It's on the to-do list.  Not sure yet whether we want to cut a tag for the current head of main.  In the meantime you can use tofn with the appropriate entry in your `Cargo.toml` file.  See [Specifying Dependencies - The Cargo Book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).

Example: you can specify a specific commit hash with something like:
```toml
tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git", rev = "702a8b03a22c10470ae18b880808175a9c39d5b3"}
```
